spring:
  redis:
    host: localhost
    port: 6379

langchain4j:
  openai:
    apiKey: ${DEEPSEEK_API_KEY}}
    baseUrl: https://api.deepseek.com
    model: deepseek-chat
qdrant:
  url: http://localhost:6333
  apiKey: ${QDRANT_API_KEY:}
app:
  rag:
    topK: 6
    chunkSize: 1000
    chunkOverlap: 200
